USE edu;

CREATE OR REPLACE TABLE NOTICE (
	`no`			INT				NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
	`title`			VARCHAR(100)	NOT NULL,
	`desc`			VARCHAR(255)	NULL,
	`content`		TEXT(30000)		NULL,
	`regDate`		DATETIME		NOT NULL	DEFAULT NOW(),
	`modDate`	    DATETIME		NOT NULL	DEFAULT NOW()
);
