services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - N8N_HOST=hiedu.iptime.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://hiedu.iptime.org:40006
      - N8N_SECURE_COOKIE=false
      - TZ=Asia/Seoul
      - GENERIC_TIMEZONE=Asia/Seoul
      - LC_ALL:en_US.UTF-8
    ports:
      - 5500:5678
    volumes:
       - n8n_storage:/home/node/.n8n

volumes:
  n8n_storage: